root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
rules:
  "@typescript-eslint/no-explicit-any": "off"
  '@typescript-eslint/explicit-function-return-type':
    - "error"
    - allowExpressions: true
  '@typescript-eslint/no-use-before-define':
    - "error"
    - functions: false